variables:
    TUTOR_PLUGIN: mfe
    TUTOR_IMAGES: mfe
    TUTOR_PYPI_PACKAGE: tutor-mfe
    OPENEDX_RELEASE: lilac
    GITHUB_REPO: overhangio/tutor-mfe

include:
  - project: 'community/tutor-ci'
    file: 'plugin-gitlab-ci.yml'
